### ISSUE TITLE
Build instructions are missing

### ISSUE THREAD

**Issue by maxmah** [Nau3D/nau#1]
It would be nice to have a dependencies list in the readme and build instructions for people who want to casually try your software without digging through cmake configs...

**Comment by lighthouse3d** [comment]
Yes, you are absolutely right. I've added some instructions. If you need any further info please let me know.

Regards,

Antonio

**Comment by maxmah** [comment]
Thank you for the fast reply and build instructions! I was trying to follow them today and had to do the following additional steps to build Nau with examples:  a follow up questions/suggestions. I would like to build the system on 64-bit Windows using either Visual Studio 2015 or 2013, as well as Optix library. One thing which was not clear is where to put

**Comment by maxmah** [comment]
Thank you for the fast reply and build instructions! I wanted to build the system on 64-bit Windows using either Visual Studio 2015 or 2013, as well as Optix library. I was trying to follow the build instructions today but it took quite some extra steps:

I was able to download wxWidgets, and specify the path (had to set both wxWidgets_LIB_DIR and wxWidgets_ROOT_DIR); then I tried to select "OPTION_BUILD_EXAMPLES" (seems logical to look at those first...), and had a problem with missing "cpplocate", which was not mentioned in the build instructions. I had to then download and compile "cpplocate" separately, then it was accepted by Nau cmake. 

Next step, GLFW was missing, so I got the 3.2.1 version, compiled it, then had to set GLFW_INCLUDE, LIBRARY_DEBUG, LIBRARY_RELEASE and, what was the most confusing, GLFW_BINARY path (I couldn't find any .dll files so I just set it to the root folder, which was a mistake as I discovered during generation step), the GLFW_INCLUDE btw was hidden under "Advanced" option of Cmake.

Next, GLEW: same as with GLFW, only that I could use pre-compiled binaries, also confusing separation between GLEW_BINARY and GLEW_LIBRARY, which both should point to the same .lib file

Finally got the error:
 contrib/glbinding-master/source/examples/cubescape-qt/CMakeLists.txt:6
 By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.1) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake
...


Well, Qt 5.1 supports VS 2012 at most, so I had to change the requirement to 5.8, and also set QtCore_DIR path to c:\Qt\Qt5.8.0\5.8\msvc2015_64\lib\cmake\Qt5Core\, and similar for Gui and Widgets.

Then I could finally generate the project, but still got these errors though during compiling (seems that nauPhysxPlugin was not properly disabled during configuring):

1>------ Skipped Build: Project: generate, Configuration: Release x64 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: uninstall, Configuration: Release x64 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: update, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: comparison, Configuration: Release x64 ------
5>------ Build started: Project: glbinding-modinfo, Configuration: Release x64 ------
6>------ Build started: Project: nauPhysxPlugin, Configuration: Release x64 ------
5>  Exporting glbinding.modinfo
6>  nauPhysXInterface.cpp
6>  physXCharacterManager.cpp
4>  main.cpp
4>  glew.cpp
6>  physXParticleManager.cpp
6>  physXRigidManager.cpp
6>  physXScene.cpp
6>  physXSoftManager.cpp
4>E:\code_max\optix\nau-master\contrib\glbinding-master\source\examples\comparison\glew.cpp(4): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
6>  physXWorldManager.cpp
6>e:\code_max\optix\nau-master\plugins\physx\src\physXScene.h(4): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXScene.cpp)
6>e:\code_max\optix\nau-master\plugins\physx\src\physXWorldManager.h(4): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXWorldManager.cpp)
6>e:\code_max\optix\nau-master\plugins\physx\src\physXParticleManager.h(8): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXParticleManager.cpp)
6>e:\code_max\optix\nau-master\plugins\physx\src\physXCharacterManager.h(6): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXCharacterManager.cpp)
6>e:\code_max\optix\nau-master\plugins\physx\src\physXSoftManager.h(6): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXSoftManager.cpp)
4>E:\code_max\optix\nau-master\contrib\glbinding-master\source\examples\comparison\main.cpp(6): fatal error C1083: Cannot open include file: 'GLFW/glfw3.h': No such file or directory
6>e:\code_max\optix\nau-master\plugins\physx\src\physXWorldManager.h(4): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\nauPhysXInterface.cpp)
6>e:\code_max\optix\nau-master\plugins\physx\src\PhysXRigidManager.h(7): fatal error C1083: Cannot open include file: 'PxPhysicsAPI.h': No such file or directory (compiling source file E:\code_max\optix\nau-master\plugins\physx\src\physXRigidManager.cpp)
7>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 2 failed, 15 up-to-date, 4 skipped ==========

**Comment by lighthouse3d** [comment]
Hi,

Thanks for the feedback :-)

The option "OPTION_BUILD_EXAMPLES" is not to be set using Nau. This option is only for one of the APIs used by Nau and it will build exeamples for that API. If you set it you'll be building the examples for that API, not for Nau. Not setting that option should avoid all the problems you describe.

That is not clear, and you're right, it seems as if one is building examples for Nau but that is not the case. I have to figure out a way of removing all those options not related to Nau from CMake ...

Best Regards,

António
